# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Dockerfile                                         :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: celestin <celestin@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/09/27 22:49:42 by celestin          #+#    #+#              #
#    Updated: 2020/09/27 23:08:17 by celestin         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

FROM    alpine:latest

LABEL   maintainer="Célestin (cmeunier@42.fr)"

# Update and upgrade apt
RUN     apk update
